In [2]:
import requests
from bs4 import BeautifulSoup


# Make a request to the webpage
url = 'http://klogic.kmutnb.ac.th:8080/kris/tess/dataQuerySelector.jsp?query=examTab'
response = requests.get(url)
#print(response.text)
# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table with the specified HTML code
table = soup.find('table', {'align': 'center', 'border': '1', 'cellpadding': '2', 'cellspacing': '0', 'width': '100%', 'bordercolor': '#CCCCCC'})

# Print the table content
print(table)

None

In [1]:
from bs4 import BeautifulSoup

# Read the HTML file
with open("dataQuerySelector.html", "r",encoding="cp874") as f:
    content = f.read()

# Use BeautifulSoup to parse the HTML content
soup = BeautifulSoup(content, "html.parser")

# Find the table in the HTML document
table = soup.find_all("table")[4]

x=0
# Extract the rows and cells of the table
rows = table.find_all("tr")
for row in rows:
    cells = row.find_all("td")
    for cell in cells:
        if x <3:
            x+=1
        else:
            print(cell.text.strip())

010113138 CIRCUITS AND ELECTRONICS
		3(3-0)

พฤ. 30/3/2566  13:00-16:00
010113139 CIRCUITS AND ELECTRONICS LAB
		1(0-1)


010113941 PROJECT I
		3(0-3)


010113942 PROJECT II
		3(0-3)


010123103 ALGORITHMS AND DATA STRUCTUR
		3(2-1)

จ. 3/4/2566  13:00-16:00
010123118 COMPUTER NETWORKS
		3(3-0)

อ. 28/3/2566  9:00-12:00
010123120 EMBEDDED SYSTEM DESIGN LABOR
		1(0-1)


010123121 DATABASE SYSTEMS
		3(3-0)

จ. 27/3/2566  9:00-12:00
010123124 COMPUTER ENGINEERING SEMINAR
		2(1-1)


010123128 COMPUTER NETWORKS LABORATORY
		1(0-1)


010123132 SOFTWARE DEVELOPMENT PRACTIC
		3(0-3)


010123134 COMPUTER ORGANIZATION
		3(3-0)

ศ. 7/4/2566  9:00-12:00
010123135 LINEAR ALGEBRA
		3(3-0)

ศ. 31/3/2566  13:00-16:00
010123201 NUMERICAL METHODS FOR COMPUT
		3(3-0)

อ. 28/3/2566  13:00-16:00
010123213 ARTIFICIAL INTELLIGENCE
		3(3-0)

อ. 4/4/2566  9:00-12:00
010123224 REAL TIME OPERATION SYSTEMS
		3(3-0)

อ. 4/4/2566  13:00-16:00
010123301 PRE-COOPERATIVE EDUCATION
		2(1-1)


010123303 CO-OPERATIVE EDUCATION II
		3(0-3)


040203100 GENERAL MATHEMATICS
		3(3-0)
อ. 31/1/2566 9:00-12:00
อ. 4/4/2566  9:00-12:00
040203111 ENGINEERING MATHEMATICS I
		3(3-0)
จ. 30/1/2566 9:00-12:00
ศ. 31/3/2566  9:00-12:00
040203112 ENGINEERING MATHEMATICS II
		3(3-0)
จ. 30/1/2566 9:00-12:00
ศ. 31/3/2566  9:00-12:00
040313005 PHYSICS I
		3(3-0)
ศ. 3/2/2566 9:00-12:00
จ. 27/3/2566  9:00-12:00
040313007 PHYSICS II
		3(3-0)
ศ. 3/2/2566 9:00-12:00
จ. 27/3/2566  9:00-12:00
040313008 PHYSICS LABORATORY II
		1(0-1)

จ. 27/3/2566  13:00-15:00
040503001 STATISTICS IN EVERYDAY LIFE
		3(3-0)
พ. 1/2/2566 9:00-12:00
ศ. 7/4/2566  9:00-12:00
080103002 ENGLISH II
		3(3-0)
พฤ. 2/2/2566 9:00-12:00
อ. 28/3/2566  9:00-12:00
080103018 ENGLISH FOR WORK
		3(3-0)
จ. 30/1/2566 9:00-12:00
พ. 29/3/2566  9:00-12:00
080103034 ENGLISH CONVERSATION
		3(3-0)


080203901 MAN AND SOCIETY
		3(3-0)
อ. 31/1/2566 13:00-15:00
จ. 27/3/2566  13:00-16:00
080203905 ECONOMY AND EVERYDAY LIFE
		3(3-0)
อ. 31/1/2566 13:00-15:00
พฤ. 30/3/2566  13:00-16:00
080203906 ECONOMICS FOR INDIVIDUAL DEV
		3(3-0)
อ. 31/1/2566 13:00-15:00
อ. 28/3/2566  13:00-16:00
080203907 BUSINESS AND EVERYDAY LIFE
		3(3-0)
อ. 31/1/2566 13:00-15:00
อ. 28/3/2566  13:00-16:00
080303103 PSYCHOLOGY FOR HAPPY LIFE
		3(3-0)
อ. 31/1/2566 13:00-16:00
พ. 29/3/2566  9:00-12:00
080303501 BASKETBALL
		1(0-1)


080303502 VOLLEYBALL
		1(0-1)


080303505 TABLE TENNIS
		1(0-1)


080303601 HUMAN RELATIONS
		3(3-0)
จ. 30/1/2566 13:00-16:00
พ. 29/3/2566  9:00-12:00
080303701 DESIGN THINKING
		3(3-0)

In [6]:
import sqlite3
from bs4 import BeautifulSoup

# Read the HTML file with the correct encoding
with open("dataQuerySelector.html", "r", encoding="cp874") as f:
    content = f.read()

# Use BeautifulSoup to parse the HTML content
soup = BeautifulSoup(content, "html.parser")

# Find the table in the HTML document
table = soup.find("table")

# Extract the rows and cells of the table
rows = table.find_all("tr")

# Connect to the database
conn = sqlite3.connect("db.sqlite3")
c = conn.cursor()

# Create the table if it doesn't exist
c.execute("CREATE TABLE IF NOT EXISTS courses (code TEXT, name TEXT, credit TEXT, date TEXT, time TEXT)")

# Loop through each row of the table and insert the data into the database
for row in rows:
    cells = row.find_all("td")
    if len(cells) == 4:
        print('1')
        code = cells[0].text.strip()
        name = cells[1].text.strip()
        credit = cells[2].text.strip()
        date_time = cells[3].text.strip().split()
        date = date_time[0]
        time = date_time[1]
        c.execute("INSERT INTO courses (code, name, credit, date, time) VALUES (?, ?, ?, ?, ?)", (code, name, credit, date, time))

# Commit the changes and close the connection
conn.commit()
conn.close()

In [7]:
#Connecting to sqlite
conn = sqlite3.connect('w3.db')

#Creating a cursor object using the cursor() method
cursor = conn.cursor()

#Doping EMPLOYEE table if already exists
cursor.execute("DROP TABLE subjects_test_date")
print("Table dropped... ")

#Commit your changes in the database
conn.commit()

#Closing the connection
conn.close()

OperationalError: no such table: subjects_test_date

In [ ]:
from bs4 import BeautifulSoup
import re
# Read the HTML file
with open("dataQuerySelector.html", "r",encoding="cp874") as f:
    content = f.read()

# Use BeautifulSoup to parse the HTML content
soup = BeautifulSoup(content, "html.parser")

# Find the table in the HTML document
table = soup.find_all("table")[4]

x=0
y=0

pattern = r"(\d+)([A-Za-z ]+)"


# Extract the rows and cells of the table
rows = table.find_all("tr")
for row in rows:
    if x <1:
        x+=1
    else:
        cells = row.find_all("td")
        for cell in cells:
            if y==0:
                print(cell.text)
'''                course_code_str = cell.text
                match = re.match(pattern, course_code_str)
                if match:
                    num_code = match.group(1)
                    text_code = match.group(2)
                print("Numeric code:", num_code)
                print("Text code:", text_code)
                y+=1
            elif y==1:
                print(cell.text +"\n")
                y+=1
            elif y==2:
                print(cell.text+"\n")
                y+=1
            elif y==4:
                print(cell.text+"\n")
                y=0'''

In [4]:

from bs4 import BeautifulSoup
import pandas as pd
import sqlite3

subjects = []
mid = []
final = []

first_Tag = 0

# Read the HTML file
with open("dataQuerySelector.html", "r",encoding="cp874") as f:
    content = f.read()

# Use BeautifulSoup to parse the HTML content
soup = BeautifulSoup(content, "html.parser")

# Find the table in the HTML document
table = soup.find_all("table")[4]

conn = sqlite3.connect("w3.db")
c = conn.cursor()

for row in table.find_all('tr'):
   
    if first_Tag == 0 :

        cells = [cell.get_text().strip() for cell in row.find_all('td')]

        # append the text to the appropriate list
        # data = {cells[0]: subjects, cells[1]: mid, cells[2]: final}

        first_Tag = 1
        
    else :

    # extract the text from each cell in the row

        cells = [cell.get_text().strip() for cell in row.find_all('td')]

        # clear pattern '\n\t\t3' that compound in tag
        cells[0] = cells[0].replace('\n\t\t', ' ')
        
        # append the text to the appropriate list
        subjects.append(cells[0])
        mid.append(cells[1])
        final.append(cells[2])

        c.execute("INSERT INTO app_select_subjects_test_date (name,mid,final) VALUES (?, ?, ?)", (cells[0],cells[1],cells[2]))

#Commit your changes in the database
conn.commit()

#Closing the connection
conn.close()

data = {'name': subjects, 'mid': mid, 'final': final}
df = pd.DataFrame(data)
print(df)

                                             name                       mid  \
0       010113138 CIRCUITS AND ELECTRONICS 3(3-0)
1   010113139 CIRCUITS AND ELECTRONICS LAB 1(0-1)
2                      010113941 PROJECT I 3(0-3)
3                     010113942 PROJECT II 3(0-3)
4   010123103 ALGORITHMS AND DATA STRUCTUR 3(2-1)
5              010123118 COMPUTER NETWORKS 3(3-0)
6   010123120 EMBEDDED SYSTEM DESIGN LABOR 1(0-1)
7               010123121 DATABASE SYSTEMS 3(3-0)
8   010123124 COMPUTER ENGINEERING SEMINAR 2(1-1)
9   010123128 COMPUTER NETWORKS LABORATORY 1(0-1)
10  010123132 SOFTWARE DEVELOPMENT PRACTIC 3(0-3)
11         010123134 COMPUTER ORGANIZATION 3(3-0)
12                010123135 LINEAR ALGEBRA 3(3-0)
13  010123201 NUMERICAL METHODS FOR COMPUT 3(3-0)
14       010123213 ARTIFICIAL INTELLIGENCE 3(3-0)
15   010123224 REAL TIME OPERATION SYSTEMS 3(3-0)
16     010123301 PRE-COOPERATIVE EDUCATION 2(1-1)
17     010123303 CO-OPERATIVE EDUCATION II 3(0-3)
18           040203100 GENERAL MATHEMATICS 3(3-0)   อ. 31/1/2566 9:00-12:00
19     040203111 ENGINEERING MATHEMATICS I 3(3-0)   จ. 30/1/2566 9:00-12:00
20    040203112 ENGINEERING MATHEMATICS II 3(3-0)   จ. 30/1/2566 9:00-12:00
21                     040313005 PHYSICS I 3(3-0)    ศ. 3/2/2566 9:00-12:00
22                    040313007 PHYSICS II 3(3-0)    ศ. 3/2/2566 9:00-12:00
23         040313008 PHYSICS LABORATORY II 1(0-1)
24   040503001 STATISTICS IN EVERYDAY LIFE 3(3-0)    พ. 1/2/2566 9:00-12:00
25                    080103002 ENGLISH II 3(3-0)   พฤ. 2/2/2566 9:00-12:00
26              080103018 ENGLISH FOR WORK 3(3-0)   จ. 30/1/2566 9:00-12:00
27          080103034 ENGLISH CONVERSATION 3(3-0)
28               080203901 MAN AND SOCIETY 3(3-0)  อ. 31/1/2566 13:00-15:00
29     080203905 ECONOMY AND EVERYDAY LIFE 3(3-0)  อ. 31/1/2566 13:00-15:00
30  080203906 ECONOMICS FOR INDIVIDUAL DEV 3(3-0)  อ. 31/1/2566 13:00-15:00
31    080203907 BUSINESS AND EVERYDAY LIFE 3(3-0)  อ. 31/1/2566 13:00-15:00
32     080303103 PSYCHOLOGY FOR HAPPY LIFE 3(3-0)  อ. 31/1/2566 13:00-16:00
33                    080303501 BASKETBALL 1(0-1)
34                    080303502 VOLLEYBALL 1(0-1)
35                  080303505 TABLE TENNIS 1(0-1)
36               080303601 HUMAN RELATIONS 3(3-0)  จ. 30/1/2566 13:00-16:00
37               080303701 DESIGN THINKING 3(3-0)

                         final
0   พฤ. 30/3/2566  13:00-16:00
1
2
3
4     จ. 3/4/2566  13:00-16:00
5     อ. 28/3/2566  9:00-12:00
6
7     จ. 27/3/2566  9:00-12:00
8
9
10
11     ศ. 7/4/2566  9:00-12:00
12   ศ. 31/3/2566  13:00-16:00
13   อ. 28/3/2566  13:00-16:00
14     อ. 4/4/2566  9:00-12:00
15    อ. 4/4/2566  13:00-16:00
16
17
18     อ. 4/4/2566  9:00-12:00
19    ศ. 31/3/2566  9:00-12:00
20    ศ. 31/3/2566  9:00-12:00
21    จ. 27/3/2566  9:00-12:00
22    จ. 27/3/2566  9:00-12:00
23   จ. 27/3/2566  13:00-15:00
24     ศ. 7/4/2566  9:00-12:00
25    อ. 28/3/2566  9:00-12:00
26    พ. 29/3/2566  9:00-12:00
27
28   จ. 27/3/2566  13:00-16:00
29  พฤ. 30/3/2566  13:00-16:00
30   อ. 28/3/2566  13:00-16:00
31   อ. 28/3/2566  13:00-16:00
32    พ. 29/3/2566  9:00-12:00
33
34
35
36    พ. 29/3/2566  9:00-12:00
37

In [6]:

import re
from bs4 import BeautifulSoup
from django.db import connection

def get_test_date() :

    first_Tag = 0

    # Read the HTML file
    with open("dataQuerySelector.html", "r",encoding="cp874") as f:
        content = f.read()

    # Use BeautifulSoup to parse the HTML content
    soup = BeautifulSoup(content, "html.parser")

    # Find the table in the HTML document
    table = soup.find_all("table")[4]


    for row in table.find_all('tr'):
    
        if first_Tag == 0 :

            cells = [cell.get_text().strip() for cell in row.find_all('td')]


            first_Tag = 1
            
        else :
            print("\n")
        # extract the text from each cell in the row

            cells = [cell.get_text().strip() for cell in row.find_all('td')]

            # clear pattern '\n\t\t3' that compound in tag
            cells[0] = cells[0].replace('\n\t\t', ' ')

            #print(cells[1])

            pattern1 = r"(\d+)([A-Za-z ]+)(\d+)"
            match1 = re.match(pattern1, cells[0])
            if match1:
                sub_code = match1.group(1)
                sub_name = match1.group(2)
                sub_credit = match1.group(3).strip()
                print("code : " + sub_code)
                print("name : " + sub_name)
                print("credit : " + sub_credit)

            mid = cells[1].split()

            if len(mid) > 0 :
                mid_numday = mid[1]
                mid_time = mid[2]
                mid_starttime,mid_endtime = mid_time.split("-")

                print("mid_numday : " + mid_numday)
                print("mid_starttime : " + mid_starttime)
                print("mid_endtime : " + mid_endtime)

            fin = cells[2].split()
        
            if len(fin) > 0 :
                fin_numday = fin[1]
                fin_time = fin[2]
                fin_starttime,fin_endtime = fin_time.split("-")

                print("fin_numday : " + fin_numday)
                print("fin_starttime : " + fin_starttime)
                print("fin_endtime : " + fin_endtime)

SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.